### ISSUE TITLE
[M1] Non-Functional Requirements

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#15]
Performance Requirements
Safety and Security Requirements

**Comment by TheRealDexipher** [comment]
NFR1: The system shall provide a feature to present content in multi-lingual.
NFR2: The system shall include an account locking feature that locks the user out after a certain number of login attempts to prevent accounts from being compromised.
NFR3: The system shall be available to users at all times. Downtime shall not occur 5hrs before the end of Monday and Wednesday.
NFR4: Administrator must be able to create, delete, edit and view all accounts.
NFR5: Managers must be able to access the manager's account.
NFR6: Manager’s account must be able to allocate jobs, view staff’s workload and availability.
NFR7: Staff must be able to access their account which allows them to submit availability.
NFR8: Staff must be able to view their assigned job and have the choice to accept or reject them.
NFR9: Database system must be updated when changes or new edits are made by the administrator, manager and staff. 
NFR10: The workload management system must be able to guarantee good response time within a five to ten-millisecond range.
NFR11: The workload management system must meet specified deadlines. Otherwise, reject responses that are past the deadlines.
NFR12: System database has a proxy server installed to encrypt any data traveling through it.
NFR13: Ensure that the system database is regularly backed up.
NFR14: Ensure that physical databases are secure and that physical access is only given to authorised personnel.
NFR15: Administrator, manager and staff have their own unique login credentials that grants them their respective access within the system.
