### ISSUE TITLE
[M1] Individual Members Task Reflections

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#20]

**Comment by TheRealDexipher** [comment]
Lee Hui Fang Anne
So far in the course, we have worked together as a team and came up with questions to ask in the client meeting that was held in week 3. From there, the functional and non-functional requirements were crafted. In Milestone 1 (M1), I took part in doing the use case descriptions, software estimation and the gantt chart. If I was given another chance, I would have phrased the questions better in order to get more information from the client. Another thing that I would do differently is to distribute the work evenly so that there would not need to be a rush to finish it all nearing the due date. In a nutshell, I have learnt that communication is key, teamwork and how to better phrase the questions during client meetings, such that the client will understand the question better. 

Dylan Teo
Throughout this course, the team has bonded and worked well together. I’ve learnt many different things from this course such as how an interaction with a client would proceed and the requirements of starting a project. For our first milestone, I took part in the construction of use-case diagrams, Gantt charts and a few other pieces stated in the Gantt Chart. We worked mostly as a team and got work done during discussions or even during labtorials. If given another chance the one thing one I would want to do better is be more prepared for the client meeting. As it was my first time for such a scenario, I thought I was prepared when going into the meeting. However, I learnt that asking the right questions are more important and bombarding the clients with questions that I thought were important.  Overall I’ve learnt the importance of teamwork and how to deal with clients, as well as preparing documents or information for the client’s project.

Poh Wee Yee
Through the past 4 weeks working with my team, I have learnt the importance of crafting the right questions to ask your client during the client meeting and the importance of teamwork in a group. Based on the information given by the client as well as the project description, we are able to craft out the functional and non-functional requirements. In Milestone 1 (M1), I took part in doing the project description, use case model, use case descriptions, user requirements, product functionality and the introduction part of this document. If I were given another chance, I would phrase the questions for the client meeting better so that my group could get better information and not make assumptions. Another thing that I would like to do better is to understand the use case diagram better so that I do not need to redo the use case model multiple times.

Toh Xin Yi
Through Milestone 1, I gained valuable knowledge on the process of planning a software development system. From requirements analysis, project estimation to scheduling and project management, I was able to develop a better understanding of each process by applying what was taught, reinforcing my knowledge. Furthermore, I now understand the importance of having in-depth planning and writing specifications as it helps to develop an effective outline and identify objectives for the system. Hence, catching problems before they affect the development process. 

In Milestone 1, I took part in doing the use case descriptions, related background description, product functionality, assumptions and dependencies, functional, non-functional, safety and security requirements. What I would have done differently was narrow down the job descriptions so that we have a clearer view of the specific requirements. It would have helped us with coming up with crucial questions for the client meeting instead of getting confirmation of our assumptions from the project descriptions. As a team, we could have distributed our individual tasks at the start of the report writing so that everyone gets an even share of work done. Overall, establishing team communication would have helped with completing this project efficiently.
