### ISSUE TITLE
[M1] Product Scope

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#5]

**Comment by TheRealDexipher** [comment]
The scope of the product is to provide a visual representation of the company's manpower. The product will be used by managers to better handle workload management of staff so that they can have a better work-life balance, staff to indicate their availabilities, and IT administrators to add and remove managers and staff into the system. The purpose of the workload management system is to provide employees with an efficient and simple tool to help manage the work allocation process. It should be convenient for all employees to access the system.

This product aims to improve how workload is managed and handled through the use of a web application that employees can access anytime to make changes to their availabilities and allocated workload. Additionally, going digital allows all the data to be stored in a separate cloud service so that data will not be compromised even if data loss were to occur.
