### ISSUE TITLE
[M3] Individual Members Task Reflections

### ISSUE THREAD

**Issue by xinyi-toh** [SIT-P5-7/ICT2201_P5-7#64]
Each member is required to write no more than 2 paragraphs of what they have done for 
milestone one, what they have learned, how they were to do it differently if they are given another 
chance to do it again, and as a team what can be done better.

**Comment by TheRealDexipher** [comment]
Lee Hui Fang Anne
In Milestone 3, the main parts are black-box testing, white-box testing, and prototype & wireframes. My main task is black-box testing, wireframes, and project management. For the wireframe, I did the login pages for the admin, manager, and staff, creating, editing, and deactivating the account. For black-box testing, I did the system state diagram, decision tables, and test case tables. I also made changes to the project management by adding on what was done with the wireframes. Throughout this whole module, I learned that time management is key. This is because I spent too much time on the wireframe and realizing that there were changes to be made to the test case tables. From these changes, the wireframe will then need to be adjusted to meet the requirements of the test cases. If I was given another chance, I will start working on the wireframe earlier and know what test cases are needed to be able to finish up the wireframe without making many changes to it. Overall, working as a team has made me realize that all members need to contribute in order to get things done on time and not rush with the overall submission as there are too many requirements to be fulfilled. 

Dylan Teo
For the whole journey of Introduction to Software Engineering module, I picked up many useful life skills and technical skills from Milestone 1 to Milestone 3. For milestone 3 specifically as we are reaching the end goals of the project, the main highlights was the black box and white box testing. To ensure the finalizing and checks on how the supposed program should turn out. One of the issues faced was having to constantly edit different portions of the project. As most parts sync-ed, one change would require change on another part of the project. So if everyone is doing different parts of the project, it would get too messy and a lot of changes are required at different parts of the project. What could have been done better is to decide on completing one task before moving on to the other. By doing so, changes are controlled and minimal, even if there is a need to change the initial completed portion, it would still be easier to keep track. Overall learning how to work as a team with respect to how it would be in the real world was an eye opener and I learnt that there is only so much one person can do and it would require a team to make a project whole. Learning how to communicate and delegate is an important skill to have when working as a team as well.

Poh Wee Yee
In Milestone 3, my main task is white-box testing which includes the pseudo-code, control flow graph, cyclomatic complexity calculation, and test cases for the full path coverage. In addition, I assisted in parts of the black-box testing like crafting some test cases and filling in parts of the decision state table. I also made changes to the class diagram according to the feedback given for our milestone 2 report. Throughout this milestone, I have learned that a software engineer needs to go through many different tedious tests for the software to be as bug-free as possible using quality test cases crafted for each use case, and not every test case may be covered as there are too many possibilities which may cause you to miss out a few. If given another chance to do it all over again, I would start thinking of the different test cases for the different use case ahead of time and spread the workload evenly as each task holds a significant amount of load to be completed using a long period of time. All in all, this Software Engineering project has taught me that in order to get things done everyone in the group needs to coordinate and complete their tasks on their own time so that the workload does not pile up to a point where things are rushed and the quality of the work drops with it.

Toh Xin Yi 
In Milestone 3, I took up tasks for the black-box testing, prototype, and wireframe. For black-box testing, I did the system state diagram, decision table, and test case tables. While completing the black-box testing, I realised the importance of ensuring that all states and test cases are considered and covered in order to do up the prototype testing. I had to make changes to the system state diagram along the way as I progressed with the decision table and test cases. Initially, I found the test case tables rather redundant and repetitive, however, it helped greatly in terms of ensuring that the wireframe consists of all possible scenarios and resulted in a comprehensive wireframe. For the prototype and wireframe, I did all the required functions and features of the staff and manager page. Throughout the entire Software Engineering project from M1 to M3, I found the GitHub project board rather useful as my team could collaboratively assign tasks to each other and keep track of one another’s progress. This helped to ensure that the team is effective and that the defined objectives are achieved which kept us in check throughout the milestones. What I would have done differently is to plan ahead for the tasks to be completed and set datelines to ensure that there is time allocated to cross-check the work done instead of rushing through the tasks which resulted in overlooking many details.
